### ISSUE TITLE
Incorrect parsing of the version field

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Hpp#14]
https://github.com/KhronosGroup/OpenXR-Hpp/blob/a582c75853737ee8269770a2732fef517ac1f9ea/scripts/template_openxr_version.hpp#L12

The current version code is assuming 32 bits for major, then 16 bits for minor and 16 bits for patch.  However, this is incorrect...  it should be 16 bits for major, 16 bits for minor and 32 bits for patch.

https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#api-version-numbers-and-semantics

**Comment by rpavlik** [comment]
oops, good catch. I've merged #16
