### ISSUE TITLE
Add optional DynamicLoader and XR_NO_PROTOTYPES to allow indirect linking

### ISSUE THREAD

**Issue by matthieucoquet** [KhronosGroup/OpenXR-Hpp#22]
As described in section 3.1.2. on the [OpenXR loader design](https://github.com/KhronosGroup/OpenXR-SDK/blob/master/doc/loader/OpenXR_loader_design.html).

The design would be really similar to Vulkan-Hpp.

OpenXR-Hpp already has a the DispatchLoaderDynamic. However, in my opinion, three things are missing to make it as easy to use as in Vulkan-Hpp:
* Add an optional DynamicLoader that will explicitly link to the loader library at run-time (via LoadLibrary on Windows for example).
* Use `XR_NO_PROTOTYPES` to optionally remove the DispatchLoaderStatic and the calls to OpenXR C functions. Using this macro, the application doesn't have to link against the OpenXR loader at build time and can link explicitly at runtime (using the DynamicLoader or something else). `XR_NO_PROTOTYPES` is already in `openxr.h` but I haven't found a way to generate is for `openxr.hpp`. Did I miss something?
* Provide a `XR_HPP_DEFAULT_DISPATCHER` similar to `VULKAN_HPP_DEFAULT_DISPATCHER`. After setting this macro to a global DispatchLoaderDynamic. The developer of the application would not have to provide the dispatcher to function calls, even for extensions functions. 

For a beginner like me, I really like the design in Vulkan-Hpp because I don't have to think about the dispatcher at all once it is set up, even when I use extensions. I also like that I'm not using the trampolines functions.

Would you be open to a contribution to add this? Or did I miss something in the generator that allow this?

**Comment by matthieucoquet** [comment]
I've been thinking about it a bit more and started to implement something.

For the DynamicLoader class, it might be simpler to just put it in another header. In Vulkan-Hpp, it's protected by `VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL`, and is enabled by default. This could be an issue because it include `windows.h` on Windows and some people don't like that.
Putting it in another header let the user decide when to include it.

Adding `XR_NO_PROTOTYPES` around the static dispatcher can be done easily using the variables protectProto and protectProtoStr.

It's also pretty easy to implement `OPENXR_HPP_DEFAULT_DISPATCHER`. But maybe people who use the static dispatcher will want two default dispatchers, like `OPENXR_HPP_DEFAULT_DISPATCHER_CORE` and `OPENXR_HPP_DEFAULT_DISPATCHER_EXT`.

I think the `DispatchLoaderDynamic` need some changes. Currently it doesn't work well when doing implicit linking.
* We should be able to fill the dispatcher in two phase. First load `xrEnumerateInstanceExtensionProperties`, `xrEnumerateApiLayerProperties` and `xrCreateInstance`. Then load everything else.
* Currently the constructor have a call to `::xrGetInstanceProcAddr`. Maybe it should also be protected with `XR_NO_PROTOTYPES`.

I want to find a way to make it convenient for both use case (as a supplement of the static dispatch or only using the dynamic dispatch). The other option would be to have two different `DispatchLoaderDynamic` but it would make it harder to understand.
I think the current static `createFullyPopulated` should be replaced by three non-static methods. Something like:
* loadInstanceCreationFunctions(PFN_xrGetInstanceProcAddr getInstanceProcAddr)
* loadAllFunctions(Instance instance)
* loadExtensionsFunctions(Instance instance)

It would be a breaking change of course so I'm open to alternative.

**Comment by rpavlik** [comment]
I think this works now, with the variation on your changes that was merged some time ago.
