### ISSUE TITLE
Generated `AsyncRequestIdFB` does not compile due to undeclared `XR_NULL_ASYNC_REQUEST_ID_FB`

### ISSUE THREAD

**Issue by KiruyaMomochi** [KhronosGroup/OpenXR-Hpp#34]
Current generated headers does not compile. The generated `AsyncRequestIdFB` struct in `openxr_atoms.hpp` uses `XR_NULL_ASYNC_REQUEST_ID_FB`, but this macro is actually not declared in `openxr.h`.

A quick workaround maybe add a global variable `NO_NULL_ATOMS` in `cpp_generator.py` and return `0` for such atoms in `computeNullAtom`.

**Comment by rpavlik** [comment]
hmm, where is it generated?

**Comment by KiruyaMomochi** [comment]
Sorry for late reply, my "current" means generating C++ projection for the latest (1.0.26) OpenXR SDK source.

The generated `AsyncRequestIdFB` struct is in file `openxr_atoms.hpp`.

https://gist.github.com/KiruyaMomochi/71688ea5246ab38a98755d508daae4fe#file-openxr_atoms-hpp-L774-L778

**Comment by rpavlik** [comment]
Hmm, I suspect that instead, we should have such atoms not have a default constructor and those methods that depend on having such a define. 0 is not inherently invalid for this atom, it appears.

**Comment by rpavlik** [comment]
Compilation fixed in #35 , re-enabled type in #37
