### ISSUE TITLE
flag bits can't be implicitly converted to flags with the | operator

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-Hpp#9]
For convenience, the following code _should_ work.

        xr::CompositionLayerFlags flags =
            xr::CompositionLayerFlagBits::BlendTextureSourceAlpha |
            xr::CompositionLayerFlagBits::CorrectChromaticAberration;

However, it fails to compile on VS 2019 with an error "No operator matches these operands"

if I manually create a freestanding `xr::CompositionLayerFlags operator |(xr::CompositionLayerFlagBits a, xr::CompositionLayerFlagBits b)` operator, then the code works.

**Comment by rpavlik** [comment]
This is fixed and in the test suite now.
